/**
 * @file CanMessageHandler.hpp
 * @brief Defines the canMessageHandler namespace.
 *
 * This file contains the canMessageHandler namespace, which includes
 * the factory function and the parseCanFrame function for handling CAN
 * messages.
 */

#ifndef CAN_MESSAGE_HANDLER_HPP
#define CAN_MESSAGE_HANDLER_HPP

#include "CanMessage.hpp"
#include <array>
#include <functional>
#include <unordered_map>

/**
 * @namespace CanMessageHandler
 * @brief Namespace for handling CAN messages.
 *
 * Encapsulates factory functions and message parsing logic for CAN messages.
 */
namespace CanBus::CanMessageHandler {

constexpr uint8_t MAGIC_HASH_KEY = 31;

struct CanMessageKey {
  CANID id;
  std::array<uint8_t, MAX_CAN_FRAME_SIZE> muxIds;

  [[nodiscard]] auto operator==( const CanMessageKey &other ) const -> bool {
    return id == other.id && muxIds == other.muxIds;
  }
};

/**
 * @brief Struct holds CAN message hash
 *
 */
struct CanMessageKeyHash {
  [[nodiscard]] auto operator()( const CanMessageKey &k ) const -> std::size_t {
    std::size_t h1 = std::hash<CANID>{}( k.id );
    std::size_t h2 = 0;
    for ( auto mux : k.muxIds ) {
      if ( mux == CAN_FRAME_DATA_MARKER ) {
        break;
        h2 = h2 * MAGIC_HASH_KEY + std::hash<uint8_t>{}( mux );
      }
    }
    return h1 ^ ( h2 << 1 ); // Combine the two hash values
  }
};

// Factory Function Type
using CanMessageFactory = std::function<std::unique_ptr<CanMessageBase>( const can_frame & )>;

/**
 * @brief struct holds factory function and associated Mux IDs
 *
 */
struct FactoryEntry {
  std::array<uint8_t, MAX_CAN_FRAME_SIZE> muxIds;
  CanMessageFactory factory;
};

/**
 * @brief create a table that can be looked up on each can frame coming in.
 *        (NOTE: this table will be AUTOGENERATED with the
 * generate_can_sources.cmake)
 *
 */
extern const std::unordered_map<CanMessageKey, CanMessageFactory, CanMessageKeyHash> CAN_MESSAGE_FACTORIES;

/**
 * @brief Parses a CAN frame and creates an appropriate CanMessage object.
 *
 * This function parses the given CAN frame based on the CAN ID and MUX ID.
 * It looks for a match in the CAN_MESSAGE_FACTORIES table. If a match is found,
 * it creates and returns an instance of the corresponding CanMessage.
 *
 * @param frame The CAN frame to parse.
 * @return std::unique_ptr<CanMessageBase> A unique pointer to the created
 * CanMessage object, or nullptr if no matching factory is found.
 */
auto parseCanFrame( const can_frame &frame ) -> std::unique_ptr<CanMessageBase>;
} // namespace CanBus::CanMessageHandler

#endif // CAN_MESSAGE_HANDLER_HPP
