/**
 * @file      ExampleCANMessage.hpp
 * @brief     Defines Can Message EXAMPLE signals as defined by the Reverse_DBC_2_1.csv DBC File.
 *            (AUTOGENERATED FILE!!!!)
 */
#ifndef EXAMPLE_MESSAGE_HPP_
#define EXAMPLE_MESSAGE_HPP_

#include "CanMessage.hpp"

// Append the following messages with the correct CANID enum.

using EXAMPLE = CanMessage<CANID::example, CAN_FRAME_DATA_MARKER, CAN_FRAME_DATA_MARKER, CAN_FRAME_DATA_MARKER,
                            CAN_FRAME_DATA_MARKER, CAN_FRAME_DATA_MARKER, CAN_FRAME_DATA_MARKER, CAN_FRAME_DATA_MARKER,
                            CAN_FRAME_DATA_MARKER>;

template <>
class CanMessage<CANID::example, CAN_FRAME_DATA_MARKER, CAN_FRAME_DATA_MARKER, CAN_FRAME_DATA_MARKER,
                 CAN_FRAME_DATA_MARKER, CAN_FRAME_DATA_MARKER, CAN_FRAME_DATA_MARKER, CAN_FRAME_DATA_MARKER,
                 CAN_FRAME_DATA_MARKER> : public CanMessageBase {

public:
  CanMessage( const can_frame &frame ) : CanMessageBase( frame, CANID::example, CanBus::MuxIDConstants::EXAMPLE ){};

  CanMessage() : CanMessageBase( CANID::example, CanBus::MuxIDConstants::EXAMPLE ){};

  /**
   * @brief Get realData
   *
   * @return double
   *
   */
  [[nodiscard]] auto realData() const -> double {
    // cantype = Real,
    // encoding = 40|16@1+,range = [-15.687|15.687],scale = (0.000488281,-15.687),units = mps2,,,
    // Start at bit 40 and read in 16 bits
    // value = ((raw * scale)+offset)

    const double ABS_LATERAL_ACCELERATION_MPS2_SCALE = 0.000488281;
    const double ABS_LATERAL_ACCELERATION_MPS2_OFFSET = -15.687;

    return ( ( extractSignal<double>( BIT_POSITION_40, BIT_POSITION_16, CanFormatType::little_endian ) *
               ABS_LATERAL_ACCELERATION_MPS2_SCALE ) +
             ABS_LATERAL_ACCELERATION_MPS2_OFFSET );
  }


};

#endif // EXAMPLE_MESSAGE_HPP_
